// This file was auto-generated by Quasalang

// import enUS from './en-US'
import hr from './hr'
import sr from './sr'
import sl from './sl'

export default {
  // 'en-US': enUS, // English
  hr, // Croatian
  sr, // Serbian
  sl // Slovenian
}
